name: Build Docker

on:
  push:
    paths:
      - "src/alpine/**"
  workflow_dispatch:

permissions:
  actions: read
  contents: read
  packages: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Metadata
        id: metadata
        uses: docker/metadata-action@v4
        with:
          images: "ghcr.io/hiroxto/training-ghcr-alpine"
          tags: |
            type=ref,event=branch
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
            type=sha

      - name: Build and Push
        uses: docker/build-push-action@v5
        with:
          push: true
          context: ./src/alpine
          file: ./src/alpine/Dockerfile
          tags: '${{ steps.metadata.outputs.tags }}'
          labels: '${{ steps.metadata.outputs.labels }}'
          platforms: linux/amd64
          cache-from: type=gha
          cache-to: type=gha,mode=max
          build-args: |
            IMAGE_TAG=${{ steps.metadata.outputs.version }}
            COMMIT_ID=${{ github.sha }}
          provenance: false
