name: Build alpine

on:
  push:
    branches:
      - main
    paths:
      - src/alpine/**
  workflow_dispatch:

permissions:
  packages: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: build
        with:
          image: ghcr.io/hiroxto/training-ghcr-alpine
          context: ./src/alpine
