name: Build alpine

on:
  push:
    branches:
      - main
    paths:
      - src/alpine/**
  workflow_dispatch:

permissions:
  packages: write

jobs:
  build:
    uses: ./.github/workflows/build.yml
    with:
      image: ghcr.io/hiroxto/training-ghcr-alpine
      context: ./src/alpine
